### PR TITLE
Rename Novatron to Gigasaur

### PR DESCRIPTION
**Pull request by ajhewitt**
The _Novatron_ was renamed to the _Gigasaur_ due to a name conflict with another project. There was also a minor update to the circuit; switching from a micro to full-sized SD card. The second bit (`bit 1`) on the expansion circuit was fixed as a logic 0, but is now wired to the write-protect pin of the SD card. This bit needs to be masked low as well to make the SD card code on the Gigasaur work correctly.

### CODE REVIEW

**Comment by lb3361** [comment]
I am sorry I did not see your pull request earlier. The rename is no problem. 

I am a bit more annoyed about the meaning change for bit 1 because this means that the novatron/gigasaur patched rom will no longer work with a number of existing expansion cards, including the latest one (all 74's) by Hans61.  Therefore I cannot submit a ROMv6 with the patch enabled by default anymore (since the main purpose of the gigatron-rom repository is to support the Gigatron, not the Gigasaur...)

I have to find another way to enable all these options...

**Comment by ajhewitt** [comment]
I can leave bit 1 as a logic `0`. In fact the GAL on the boards I have shipped are programmed this way. The write protect pin on the SD card is wired up to a spare pin on the GAL with the (possible future) option to route that to bit 1 on the bus. I haven't made this change to the GAL yet and may never do it. I can revert this change and just leave the name change in place.

**Comment by lb3361** [comment]
It would be safer to write the write-protect signal to one of the high bits instead of one of the already assigned bits.

**Comment by lb3361** [comment]
I implemented the pull request in a different manner, with a mask that can be defined at compile time.
The default mask is 0x3 as discussed earlier.

**Pull request closed without merging**
